performance_score_features:
  - avg_speed_diff
  - avg_g1_finish
  - avg_g2_finish
  - avg_g3_finish
  - log_avg_prize_money

not_model_features:
  - race_score
  - race_score_pred
  - race_score_pred_diff
  - horse_name
  - horse_racing_api_id
  - avg_speed_diff
  - avg_g1_finish
  - avg_g2_finish
  - avg_g3_finish
  - log_avg_prize_money
  - total_prize_money
  - num_races
  - racing_api_id
  - sire_id
  - dam_name
  - sire_name
  - dam_id
  - damdam_id
  - damdamdam_id
  - damdamsire_id
  - damsire_id
  - damsiredam_id
  - damsiresire_id
  - siredam_id
  - siredamdam_id
  - siredamsire_id
  - siresire_id
  - siresiredam_id
  - siresiresire_id
