performance_score_features:
  - avg_speed_diff
  - avg_g1_finish
  - avg_g2_finish
  - avg_g3_finish
  - log_avg_prize_money

model_features:
  - race_score
  - race_score_dam
  - race_score_sire
  - race_score_siredam
  - race_score_siresire
  - race_score_damdam
  - race_score_damsire

  # Siblings
  - avg_dam_sibling_score
  - avg_sire_sibling_score
  - max_dam_sibling_score
  - max_sire_sibling_score
  - std_dam_sibling_score
  - std_sire_sibling_score
  - min_dam_sibling_score
  - min_sire_sibling_score

  # Cousins
  - avg_damdam_cousin_score
  - avg_damsire_cousin_score
  - avg_siresire_cousin_score
  - avg_siredam_cousin_score
  - max_damdam_cousin_score
  - max_damsire_cousin_score
  - max_siresire_cousin_score
  - max_siredam_cousin_score
  - std_damdam_cousin_score
  - std_damsire_cousin_score
  - std_siresire_cousin_score
  - std_siredam_cousin_score
  - min_damdam_cousin_score
  - min_damsire_cousin_score
  - min_siresire_cousin_score
  - min_siredam_cousin_score

  # Aunt / Uncle
  - avg_damdam_auntuncle_score
  - avg_damsire_auntuncle_score
  - avg_siresire_auntuncle_score
  - avg_siredam_auntuncle_score
  - max_damdam_auntuncle_score
  - max_damsire_auntuncle_score
  - max_siresire_auntuncle_score
  - max_siredam_auntuncle_score
  - min_damdam_auntuncle_score
  - min_damsire_auntuncle_score
  - min_siresire_auntuncle_score
  - min_siredam_auntuncle_score
  - std_damdam_auntuncle_score
  - std_damsire_auntuncle_score
  - std_siresire_auntuncle_score
  - std_siredam_auntuncle_score
